# IMPORT LIBRARIES

In [66]:
from sklearn.datasets import load_breast_cancer
import numpy as np
import pandas as pd
from scipy.spatial import distance

# READ DATASET

In [3]:
data = load_breast_cancer(as_frame=True)
data

{'data':      mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
 0          17.99         10.38          122.80     1001.0          0.11840   
 1          20.57         17.77          132.90     1326.0          0.08474   
 2          19.69         21.25          130.00     1203.0          0.10960   
 3          11.42         20.38           77.58      386.1          0.14250   
 4          20.29         14.34          135.10     1297.0          0.10030   
 ..           ...           ...             ...        ...              ...   
 564        21.56         22.39          142.00     1479.0          0.11100   
 565        20.13         28.25          131.20     1261.0          0.09780   
 566        16.60         28.08          108.30      858.1          0.08455   
 567        20.60         29.33          140.10     1265.0          0.11780   
 568         7.76         24.54           47.92      181.0          0.05263   
 
      mean compactness  mean concavity  me

# create dataframe

In [19]:
features = data.data
target = data.target
whole_data = np.c_[features, target]

feature_names = data.feature_names.tolist()
feature_names.append('class')

df = pd.DataFrame(whole_data, columns=feature_names)

In [21]:
df.head().T

0            1            2           3  \
mean radius                17.990000    20.570000    19.690000   11.420000   
mean texture               10.380000    17.770000    21.250000   20.380000   
mean perimeter            122.800000   132.900000   130.000000   77.580000   
mean area                1001.000000  1326.000000  1203.000000  386.100000   
mean smoothness             0.118400     0.084740     0.109600    0.142500   
mean compactness            0.277600     0.078640     0.159900    0.283900   
mean concavity              0.300100     0.086900     0.197400    0.241400   
mean concave points         0.147100     0.070170     0.127900    0.105200   
mean symmetry               0.241900     0.181200     0.206900    0.259700   
mean fractal dimension      0.078710     0.056670     0.059990    0.097440   
radius error                1.095000     0.543500     0.745600    0.495600   
texture error               0.905300     0.733900     0.786900    1.156000   
perimeter error             8.589000     3.398000     4.585000    3.445000   
area error                153.400000    74.080000    94.030000   27.230000   
smoothness error            0.006399     0.005225     0.006150    0.009110   
compactness error           0.049040     0.013080     0.040060    0.074580   
concavity error             0.053730     0.018600     0.038320    0.056610   
concave points error        0.015870     0.013400     0.020580    0.018670   
symmetry error              0.030030     0.013890     0.022500    0.059630   
fractal dimension error     0.006193     0.003532     0.004571    0.009208   
worst radius               25.380000    24.990000    23.570000   14.910000   
worst texture              17.330000    23.410000    25.530000   26.500000   
worst perimeter           184.600000   158.800000   152.500000   98.870000   
worst area               2019.000000  1956.000000  1709.000000  567.700000   
worst smoothness            0.162200     0.123800     0.144400    0.209800   
worst compactness           0.665600     0.186600     0.424500    0.866300   
worst concavity             0.711900     0.241600     0.450400    0.686900   
worst concave points        0.265400     0.186000     0.243000    0.257500   
worst symmetry              0.460100     0.275000     0.361300    0.663800   
worst fractal dimension     0.118900     0.089020     0.087580    0.173000   
class                       0.000000     0.000000     0.000000    0.000000   

                                   4  
mean radius                20.290000  
mean texture               14.340000  
mean perimeter            135.100000  
mean area                1297.000000  
mean smoothness             0.100300  
mean compactness            0.132800  
mean concavity              0.198000  
mean concave points         0.104300  
mean symmetry               0.180900  
mean fractal dimension      0.058830  
radius error                0.757200  
texture error               0.781300  
perimeter error             5.438000  
area error                 94.440000  
smoothness error            0.011490  
compactness error           0.024610  
concavity error             0.056880  
concave points error        0.018850  
symmetry error              0.017560  
fractal dimension error     0.005115  
worst radius               22.540000  
worst texture              16.670000  
worst perimeter           152.200000  
worst area               1575.000000  
worst smoothness            0.137400  
worst compactness           0.205000  
worst concavity             0.400000  
worst concave points        0.162500  
worst symmetry              0.236400  
worst fractal dimension     0.076780  
class                       0.000000

# select 3 random samples from each class

In [24]:
benign_samples = df[df['class'] == 0].sample(3)
benign_samples.T

4            441          400
mean radius                20.290000    17.270000    17.910000
mean texture               14.340000    25.420000    21.020000
mean perimeter            135.100000   112.400000   124.400000
mean area                1297.000000   928.800000   994.000000
mean smoothness             0.100300     0.083310     0.123000
mean compactness            0.132800     0.110900     0.257600
mean concavity              0.198000     0.120400     0.318900
mean concave points         0.104300     0.057360     0.119800
mean symmetry               0.180900     0.146700     0.211300
mean fractal dimension      0.058830     0.054070     0.071150
radius error                0.757200     0.510000     0.403000
texture error               0.781300     1.679000     0.774700
perimeter error             5.438000     3.283000     3.123000
area error                 94.440000    58.380000    41.510000
smoothness error            0.011490     0.008109     0.007159
compactness error           0.024610     0.043080     0.037180
concavity error             0.056880     0.049420     0.061650
concave points error        0.018850     0.017420     0.010510
symmetry error              0.017560     0.015940     0.015910
fractal dimension error     0.005115     0.003739     0.005099
worst radius               22.540000    20.380000    20.800000
worst texture              16.670000    35.460000    27.780000
worst perimeter           152.200000   132.800000   149.600000
worst area               1575.000000  1284.000000  1304.000000
worst smoothness            0.137400     0.143600     0.187300
worst compactness           0.205000     0.412200     0.591700
worst concavity             0.400000     0.503600     0.903400
worst concave points        0.162500     0.173900     0.196400
worst symmetry              0.236400     0.250000     0.324500
worst fractal dimension     0.076780     0.079440     0.119800
class                       0.000000     0.000000     0.000000

In [28]:
malignant_samples = df[df['class'] == 1].sample(3)
malignant_samples.T

20          46          364
mean radius               13.080000    8.196000   13.400000
mean texture              15.710000   16.840000   16.950000
mean perimeter            85.630000   51.710000   85.480000
mean area                520.000000  201.900000  552.400000
mean smoothness            0.107500    0.086000    0.079370
mean compactness           0.127000    0.059430    0.056960
mean concavity             0.045680    0.015880    0.021810
mean concave points        0.031100    0.005917    0.014730
mean symmetry              0.196700    0.176900    0.165000
mean fractal dimension     0.068110    0.065030    0.057010
radius error               0.185200    0.156300    0.158400
texture error              0.747700    0.956700    0.612400
perimeter error            1.383000    1.094000    1.036000
area error                14.670000    8.205000   13.220000
smoothness error           0.004097    0.008968    0.004394
compactness error          0.018980    0.016460    0.012500
concavity error            0.016980    0.015880    0.014510
concave points error       0.006490    0.005917    0.005484
symmetry error             0.016780    0.025740    0.012910
fractal dimension error    0.002425    0.002582    0.002074
worst radius              14.500000    8.964000   14.730000
worst texture             20.490000   21.960000   21.700000
worst perimeter           96.090000   57.260000   93.760000
worst area               630.500000  242.200000  663.500000
worst smoothness           0.131200    0.129700    0.121300
worst compactness          0.277600    0.135700    0.167600
worst concavity            0.189000    0.068800    0.136400
worst concave points       0.072830    0.025640    0.069870
worst symmetry             0.318400    0.310500    0.274100
worst fractal dimension    0.081830    0.074090    0.075820
class                      1.000000    1.000000    1.000000

# calculate distances between sample pairs

In [32]:
# extract values from df
malignant_samples_array = malignant_samples.iloc[:, :-1].values
benign_samples_array    = benign_samples.iloc[:, :-1].values

print(f"malignant_samples_array.shape: {malignant_samples_array.shape}")
print(f"benign_samples_array.shape: {benign_samples_array.shape}")

malignant_samples_array.shape: (3, 30)
benign_samples_array.shape: (3, 30)


# define functions

In [79]:
def euclidean(v, u):
    return np.linalg.norm(u - v)

def manhattan(u, v):
    return np.sum(np.abs(u - v))

def chebyshev(u, v):
    return np.max(np.abs(u - v))

def cosine(u, v):
    return 1 - (np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v)))

def mahalanobis(u, v, S):
    # Inverse covariance matrix
    S_inv = np.linalg.inv(S)
    # Mahalanobis distance
    diff = u - v
    return distance.mahalanobis(u, v, S_inv)

In [45]:
euclidean_distances1 = np.linalg.norm(benign_samples_array[:, None, :] - malignant_samples_array[None, :, :], axis=2)
euclidean_distances1

array([[1227.97315837, 1731.87415221, 1182.32649939],
       [ 773.64704688, 1275.1910549 ,  728.90325522],
       [ 826.74859225, 1330.43319321,  781.53701372]])

In [47]:
euclidean_distances2 = np.zeros((3, 3))
for i, u in enumerate(benign_samples_array):
    for j, v in enumerate(malignant_samples_array):
        euclidean_distances2[i, j] = euclidean(u, v)

euclidean_distances2

array([[1227.97315837, 1731.87415221, 1182.32649939],
       [ 773.64704688, 1275.1910549 ,  728.90325522],
       [ 826.74859225, 1330.43319321,  781.53701372]])

In [42]:
manhattan_distances1 = np.sum(np.abs(benign_samples_array[:, None, :] - malignant_samples_array[None, :, :]), axis=2)
manhattan_distances1

array([[1932.749473, 2732.120841, 1873.800973],
       [1208.308506, 2002.214072, 1144.507226],
       [1294.186196, 2088.599202, 1230.644416]])

In [43]:
manhattan_distances2 = np.zeros((3, 3))
for i, u in enumerate(benign_samples_array):
    for j, v in enumerate(malignant_samples_array):
        manhattan_distances2[i, j] = manhattan(u, v)

manhattan_distances2

array([[1932.749473, 2732.120841, 1873.800973],
       [1208.308506, 2002.214072, 1144.507226],
       [1294.186196, 2088.599202, 1230.644416]])

In [49]:
chebyshev_distances1 = np.max(benign_samples_array[:, None, :] - malignant_samples_array[None, :, :], axis=2)
chebyshev_distances1

array([[ 944.5, 1332.8,  911.5],
       [ 653.5, 1041.8,  620.5],
       [ 673.5, 1061.8,  640.5]])

In [50]:
chebyshev_distances2 = np.zeros((3, 3))
for i, u in enumerate(benign_samples_array):
    for j, v in enumerate(malignant_samples_array):
        chebyshev_distances2[i, j] = chebyshev(u, v)

chebyshev_distances2

array([[ 944.5, 1332.8,  911.5],
       [ 653.5, 1041.8,  620.5],
       [ 673.5, 1061.8,  640.5]])

In [55]:
# Normalize rows
benign_samples_array_norm = benign_samples_array / np.linalg.norm(benign_samples_array, axis=1, keepdims=True)
malignant_samples_array_norm = malignant_samples_array / np.linalg.norm(malignant_samples_array, axis=1, keepdims=True)

# Cosine similarity matrix
cosine_sim = np.dot(benign_samples_array_norm, malignant_samples_array_norm.T)

# Cosine distance
cosine_distances1 = 1 - cosine_sim
cosine_distances1

array([[0.00225834, 0.01305153, 0.00182084],
       [0.00327944, 0.01268518, 0.00320738],
       [0.0015577 , 0.0105701 , 0.00143334]])

In [51]:
cosine_distances2 = np.zeros((3, 3))
for i, u in enumerate(benign_samples_array):
    for j, v in enumerate(malignant_samples_array):
        cosine_distances2[i, j] = cosine(u, v)

cosine_distances2

array([[0.00225834, 0.01305153, 0.00182084],
       [0.00327944, 0.01268518, 0.00320738],
       [0.0015577 , 0.0105701 , 0.00143334]])

In [80]:
new_data = data = np.vstack([benign_samples_array, malignant_samples_array])
cov = np.cov(df.values[:, :-1], rowvar=False)
mahalanobis_distances2 = np.zeros((3, 3))
for i, u in enumerate(benign_samples_array):
    for j, v in enumerate(malignant_samples_array):
        mahalanobis_distances2[i, j] = mahalanobis(u, v, cov)

mahalanobis_distances2

array([[7.0446778 , 7.01233209, 5.83360965],
       [7.28855813, 6.7284842 , 5.33828531],
       [9.22825148, 9.78861805, 9.14323833]])

In [81]:
names = ["1", "2", "3"]
pair_names = [f"{i}-{j}" for i in names for j in names]
pair_names

['1-1', '1-2', '1-3', '2-1', '2-2', '2-3', '3-1', '3-2', '3-3']

In [100]:
distances_df = pd.DataFrame(columns=["pairs", "Euclidean", "Manhattan",
                                    "Chebyshev", "Cosine", "Mahalanobis"])
distances_df

Empty DataFrame
Columns: [pairs, Euclidean, Manhattan, Chebyshev, Cosine, Mahalanobis]
Index: []

In [104]:
distances_df.pairs = pair_names
distances_df.Euclidean = euclidean_distances2.flatten()
distances_df.Manhattan = manhattan_distances2.flatten()
distances_df.Chebyshev = chebyshev_distances2.flatten()
distances_df.Cosine = cosine_distances2.flatten()
distances_df.Mahalanobis = mahalanobis_distances2.flatten()
distances_df = distances_df.set_index("pairs")
distances_df

Euclidean    Manhattan  Chebyshev    Cosine  Mahalanobis
pairs                                                            
1-1    1227.973158  1932.749473      944.5  0.002258     7.044678
1-2    1731.874152  2732.120841     1332.8  0.013052     7.012332
1-3    1182.326499  1873.800973      911.5  0.001821     5.833610
2-1     773.647047  1208.308506      653.5  0.003279     7.288558
2-2    1275.191055  2002.214072     1041.8  0.012685     6.728484
2-3     728.903255  1144.507226      620.5  0.003207     5.338285
3-1     826.748592  1294.186196      673.5  0.001558     9.228251
3-2    1330.433193  2088.599202     1061.8  0.010570     9.788618
3-3     781.537014  1230.644416      640.5  0.001433     9.143238

1. فاصله اقلیدسی فکر میکند همه ویژگیها یک متر و معیار دارند. و تاثیر داده ها با معیار بزرگتر در ان بیشتر است. از طرفی اوتلایرها اثر بزرگی روی ان دارند. مگر اینکه داده ها را نرمالایز کنیم و این اثرات را از بین ببریم.
2. موارد بالا برای فاصله منهتن نیز صد میکنند منتها اثر اوتلایر در این فاصله کمتر است.
3. فاصله چبیشف بیشترین فاصله از یک ویژگی را در نظر میگیرد و مابقی را کنار میگذارد. به نوعی فکر میکند همه ویژگیها مثل هم هستند و از میان این ویژگیهای شبیه بزرگترین را برمیدارد.
4. فاصله کوسینوسی تنها زاویه را در نظر میگیرد و اندازه را کنار میگذارد. چون ممکن است اندازه در تعیین سالم یا بدخیم بودن سلول خیلی تاثیرگذار باشد.
5. فاصله ماهالانوبیس دو عمل مهم را انجام میدهد. یکی مقیاسها را یکی میکند و چالش تفاوت معیار در فاصله های فوق را حل میکند و از طرفی ستونهایی که با هم همبسته هستند را پیدا کرده و اثرشان را کم میکند. مثلا به ستون محیط، مساحت و شعاع را معیارهای وزن کمتری داده و اهمیت شعاع را برخلاف معیارهای قبلی سه بار تکرار نمیکند.

فاصله هر نمونه جدید را از مجموعه فاصله های دارای برچسب انتخاب کرده و از مثلا 3 نمونه با فاصله نزدیکتر رای گیری میکنیم و رای بیشتر به معنی تعلق نمونه به آن دسته خواهد بود.برای این مورد از فاصله ماهالانوبیس استفاده میکنیم که هم اثر مقیاس اندازه را کم کند و هم اثر ستونهای همبسته را.

فاصله اقلیدسی حساس به اوتلایر است. یعنی کنار اهمیت زیاد دادن به مقیاسها، چنانچه یک فیچر مقدار نادرستی داشته باشد وزن بیشتری به آن داده و اثر بیشتری روی فاصله میگذارد.

فاصله کوسینوسی اندازه را در نظر نمیگیرد و فقط زاویه را در محاسبات خود دخالت میدهد.مثلا دو بردار را در نظر بگیریم یکی با اندازه 2 و دیگری با 1. چنانچه بردار جدید زاویه برابر با هر دو تشکیل دهد، به هر دو اهمیت یکسان خواهد داد. در جدول بالا با وجود افزایش فاصله مابقی معیارها، فاصله کوسینوسی کاهش میابد.